### ISSUE TITLE
Calulate depth image by raw depth image

### ISSUE THREAD

**Issue by carlosInteraminense** [s-gupta/rcnn-depth#18]
How you calculate the depth image by the raw depth image? You have the code?

**Comment by LaifuLi** [comment]
Have you already fixed this problem?

**Comment by s-gupta** [comment]
We use in-painted depth as made available by Silberman et al. Please look at [this script](https://github.com/s-gupta/nyu-hooks/blob/master/script_data.m) for how the data that we use for our experiments was obtained.

Silberman et al. release code that they used for in-painting, so that can be a place to start if you want to in-paint your images. Otherwise we have a rather naive median filtering based method for in-painting images [here](https://github.com/s-gupta/rgbdutils/blob/master/fillHoles.m).

**Comment by LaifuLi** [comment]
In the toolbox of nyu_depth_v2 provided by Silberman et al., there is a demo script named demo_fill_depth_cross_bf_test.m, it shows how could we get the in-painted depth if we only have the raw depth files. 
Thank @s-gupta again for the hint!
