### ISSUE TITLE
How to change the raw depth image to the hha image?

### ISSUE THREAD

**Issue by mrzw** [s-gupta/rcnn-depth#29]

**Comment by vinodkkurmi** [comment]
@s-gupta please help us..

**Comment by s-gupta** [comment]
See: https://github.com/s-gupta/rcnn-depth/blob/master/rcnn/saveHHA.m

**Comment by xxxxxxxx-dl** [comment]
@s-gupta Hi，function HHA = saveHHA(imName, C, outDir, D, RD)
% function HHA = saveHHA(imName, C, outDir, D, RD)

% AUTORIGHTS

  if(isempty(D)), D = getImage(imName, 'depth'); end
  if(isempty(RD)), RD = getImage(imName, 'rawdepth'); end
  
  D = double(D)./1000;
  missingMask = RD == 0;
  [pc, N, yDir, h, pcRot, NRot] = processDepthImage(D*100, missingMask, C);
  angl = acosd(min(1,max(-1,sum(bsxfun(@times, N, reshape(yDir, 1, 1, 3)), 3))));
    
  % Making the minimum depth to be 100, to prevent large values for disparity!!!
  pc(:,:,3) = max(pc(:,:,3), 100); 
  I(:,:,1) = 31000./pc(:,:,3); 
  I(:,:,2) = h;
  I(:,:,3) = (angl+128-90); %Keeping some slack
  I = uint8(I);
  
  % Save if can save
  if(~isempty(outDir) && ~isempty(imName)), imwrite(I, fullfile_ext(outDir, imName, 'png')); end
  
  HHA = I;
end
in this function, what's the meaning of 31000,128-30?is it some kinect pos parameter?shall I change according to my own data?

**Comment by sumanth-nirmal** [comment]
Hi, 
I was also wondering what these parameters (31000, 128-30) mean, any insights please..?

**Comment by xxxxxxxx-dl** [comment]
Hi， I guess it's a trick to make all the calculated values to be distributed in the range of 0-255 so that it's suitable for the hha image to be visualized.

**Comment by fangyan93** [comment]
@s-gupta @xxxxxxxx-dl Hi, all, I am wondering the difference between depth data and raw depth data, I noticed that they are not the same. The data obtained from camera should be raw depth, how can I get depth image? I noticed the comment says depth image is in centimeters, but the distance in centimeters is from where to where? Could you please explain it a bit? Thanks!

**Comment by xxxxxxxx-dl** [comment]
Hi there. I think raw depth is the depth image obtained directly from sensors(Kinect, for example). Due to the occlusion and some other reasons, there are invalid data in the raw depth image. In other words, there are "holes" in raw depth images. You can use an algorithm to fill the holes. The algorithm is provided in the corresponding github page. By running the algorithm, raw depth images can be transformed into depth images. The distance is from center of the camera to objects in the scene.




发自我的 iPhone

**Comment by fangyan93** [comment]
@xxxxxxxx-dl Hello, thanks for reply. I am looking for the script to do the hole filling, I did not find something like hole_fill.m at s-guta's github pages, but I find fill_depth_colorization.m at [here](http://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html). Could you please post a link to the script? Also, I found the conversion is relatively slow, do you have idea if I want to do real time object detection using HHA image? Thank you very much!

**Comment by xxxxxxxx-dl** [comment]
Hi,the code can be downloaded here http://cs.nyu.edu/~silberman/code/toolbox_nyu_depth_v2.zip.

----- 原始邮件 -----
发件人: "fangyan xu" <notifications@github.com>
收件人: "s-gupta/rcnn-depth" <rcnn-depth@noreply.github.com>
抄送: "dinglu" <dinglu@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期三, 2017年 8 月 30日 上午 4:15:08
主题: Re: [s-gupta/rcnn-depth] How to change the raw depth image to the hha image? (#29)

@xxxxxxxx-dl Hello, thanks for reply. I am looking for the script to do the hole filling, I did not find something like hole_fill.m at s-guta's github pages, but I find fill_depth_colorization.m at [here](http://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html). Could you please post a link to the script? Also, I found the conversion is relatively slow, do you have idea if I want to do real time object detection using HHA image? Thank you very much!

**Comment by citlag** [comment]
Hi,

I am trying to convert nyu v2 images into HHA but for some reason, instead of visualizing them with mostly green color like in the example provided, my results are red. Is it normal or I am missing to do some procedure?

Hopefully you reply, thanks!

**Comment by scstu** [comment]
Dear all, Please I need your help!! 
I have depth images "uint16" and I need to compute raw depth from those images. I have tested those codes on NYUv2 depth images and it's working fine. But in my case I don't have the raw_depth images !
that's why I'm looking for a method to compute raw depth from depth image.
please! any idea will be appreciated. 

  @xxxxxxxx-dl @s-gupta @ @vinodkkurmi @sumanth-nirmal @mrzw

**Comment by xxxxxxxx-dl** [comment]
Hi~
Based on my understanding, the raw depth image is the one you captured directly from the sensor like kincet or anything else. Due to occlusion or some other reason, there are 'holes' in the raw depth image. An algorithm is used to fill those holes, which is already provided in the code package. The result is the depth image. Then you can get two images to run the code.

----- 原始邮件 -----
发件人: "scstu" <notifications@github.com>
收件人: "s-gupta/rcnn-depth" <rcnn-depth@noreply.github.com>
抄送: "dinglu" <dinglu@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期五, 2018年 5 月 04日 上午 12:21:13
主题: Re: [s-gupta/rcnn-depth] How to change the raw depth image to the hha image? (#29)

saveHHA.m requires 2 images( raw depth image and depth image), I am working on a database that contains rgb"uint8" and depth images'uint16' only.  and to create HHA encoding image using saveHHA.m I need raw depth image. so, I'm asking if there is a way to get raw depth image from depth image. or any way to get HHA encoding image from depth image only... @xxxxxxxx-dl

**Comment by scstu** [comment]
Yes, exactly.
But in my case. I am working on a database containing depth images only and to run this code I need raw image along side with depth image. I need to use HHA encoding for another task. 
so is there a way to get hha from depth image only if not, is it possible to get raw depth from depth image?
@xxxxxxxx-dl

**Comment by xxxxxxxx-dl** [comment]
Hi，
I don't think changing the raw depth to depth image is a reversible operation.
You can regard your depth image as raw depth image and use the algorithm provided in the code package 
to fill the hole to get depth image. Then you will get two sets of depth images.

----- 原始邮件 -----
发件人: "scstu" <notifications@github.com>
收件人: "s-gupta/rcnn-depth" <rcnn-depth@noreply.github.com>
抄送: "dinglu" <dinglu@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期五, 2018年 5 月 04日 下午 5:41:52
主题: Re: [s-gupta/rcnn-depth] How to change the raw depth image to the hha image? (#29)

Yes, exactly.
But in my case. I am working on a database containing depth images only and to run this code I need raw image along side with depth image. I need to use HHA encoding for another task. 
so is there a way to get hha from depth image only if not, is it possible to get raw depth from depth image?
@xxxxxxxx-dl

**Comment by 15721130626** [comment]
How to generate a depth map from raw depth map？@xxxxxxxx-dl

**Comment by 15721130626** [comment]
In you demo.m C=cropCamera(getCameraParam('color')); But I did not find Cameraparam. where can I get cameraparam? @s-gupta

**Comment by Raven1327** [comment]
Hi,

I am trying to convert nyu v2 images into HHA but for some reason, instead of visualizing them with mostly green color like in the example provided, my results are red. Is it normal or I am missing to do some procedure?

Hopefully you reply, thanks! @xxxxxxxx-dl

**Comment by sunzhen6251** [comment]
> Hi,
> 
> I am trying to convert nyu v2 images into HHA but for some reason, instead of visualizing them with mostly green color like in the example provided, my results are red. Is it normal or I am missing to do some procedure?
> 
> Hopefully you reply, thanks! @xxxxxxxx-dl

Hi,

I also have this issue, have you solved it ?

Thanks !

**Comment by chenkingwen** [comment]
I am gonna understand the algorithm of depth 2 HHA clearly. does anyone can provide the illustrate of the algorithms. Thanks very much!!!@xxxxxxxx-dl

**Comment by JigyasaK** [comment]
> Hi,
> 
> I am trying to convert nyu v2 images into HHA but for some reason, instead of visualizing them with mostly green color like in the example provided, my results are red. Is it normal or I am missing to do some procedure?
> 
> Hopefully you reply, thanks!

Hi,
I was also getting reddish HHA images from my NYU depth dataset when I was using the depth images as input. But when I switched to using Depth matrices as given in NYUdepth.mat file in the original dataset, I got normal HHA image. So maybe you should try with raw depth values, not the depth image.
